# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJhadav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import ujson
import csv
import subprocess
import cv2
from PIL import Image, ImageTk
import threading
import sys
import os
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, '../../'))
sys.path.insert(0, project_root)

import thesystem.system
import thesystem.inventory
from thesystem.misc import resource_path

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")

with open("Files/Player Data/Tabs.json",'r') as tab_son:
    tab_son_data=ujson.load(tab_son)

with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
    tab_son_data["Inventory"]='Open'
    ujson.dump(tab_son_data,fin_tab_son,indent=4)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()
stop_event=threading.Event()

initial_height = 0
target_height = 592
window_width = 855

window.geometry(f"{window_width}x{initial_height}")
job=thesystem.misc.return_status()["status"][1]["job"]

top_val='dailyquest.py'
all_prev=''
video='Video'
transp_clr='#0C679B'

if job!='None':
    top_val=''
    all_prev='alt_'
    video='Alt Video'
    transp_clr='#652AA3'

thesystem.system.make_window_transparent(window,transp_clr)

with open("Files/Player Data/Settings.json", 'r') as settings_open:
    setting_data=ujson.load(settings_open)

thesystem.system.animate_window_open(window, target_height, window_width, step=40, delay=1)

window.configure(bg = "#FFFFFF")
set_data=thesystem.misc.return_settings()
transp_value=set_data["Settings"]["Transparency"]

window.attributes('-alpha',transp_value)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

top_images = f"thesystem/{all_prev}top_bar"
bottom_images = f"thesystem/{all_prev}bottom_bar"
top_preloaded_images = thesystem.system.load_or_cache_images(top_images, (970, 40), job, type_="top")
bottom_preloaded_images = thesystem.system.load_or_cache_images(bottom_images, (970, 40), job, type_="bottom")

subprocess.Popen([sys.executable, resource_path('Files/Mod/default/sfx.py')])

def start_move(event):
    window.lastx, window.lasty = event.widget.winfo_pointerxy()

def move_window(event):
    x_root, y_root = event.widget.winfo_pointerxy()
    deltax, deltay = x_root - window.lastx, y_root - window.lasty
    if deltax != 0 or deltay != 0:
        window.geometry(f"+{window.winfo_x() + deltax}+{window.winfo_y() + deltay}")
        window.lastx, window.lasty = x_root, y_root

def ex_close(win):
    if setting_data["Settings"]["Performernce (ANIME):"] != "True":
        stop_event.set()
        if 'update_thread' in globals() and update_thread.is_alive():
            update_thread.join()

    with open("Files/Player Data/Tabs.json",'r') as tab_son:
        tab_son_data=ujson.load(tab_son)
    with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
        tab_son_data["Inventory"]='Close'
        ujson.dump(tab_son_data,fin_tab_son,indent=4)
    threading.Thread(target=thesystem.system.fade_out, args=(window, 0.8)).start()
    subprocess.Popen([sys.executable, resource_path('Files/Mod/default/sfx_close.py')])
    thesystem.system.animate_window_close(window, initial_height, window_width, step=50, delay=1)

canvas = Canvas(window, bg="#FFFFFF", height=592, width=855, bd=0, highlightthickness=0, relief="ridge")
canvas.place(x=0, y=0)

image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(479.0, 364.0, image=image_image_1)

with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    video_path=pres_file_data["Anime"][video]
    preloaded_frames=np.load(video_path)
player = thesystem.system.FastVideoPlayer(canvas, preloaded_frames, 479.0, 364.0, pause_duration=0.5)



image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(433.0, 100.0, image=image_image_4)

# --- NEW: TABBING SYSTEM ---
inventory_items = [] # This will store all item widgets and data
def show_tab(category):
    """ Hides all inventory items, then shows only the ones in the selected category. """
    current_item_index = 0
    for item in inventory_items:
        # Check if item belongs to the current tab ('All' shows everything)
        if category == "All" or item['category'] == category:
            # Calculate position in the grid for the visible item
            row = current_item_index // buttons_per_row
            col = current_item_index % buttons_per_row
            x = x_start + col * spacing_x
            y = y_start + row * spacing_y
            
            # Place the button and update canvas item coordinates
            item['widgets']['button'].place(x=x, y=y, width=70, height=70)
            canvas.coords(item['widgets']['background'], x + 35, y + 35)
            canvas.coords(item['widgets']['qty_text'], x + 65, y + 65)

            # Make canvas items visible
            canvas.itemconfig(item['widgets']['background'], state='normal')
            canvas.itemconfig(item['widgets']['qty_text'], state='normal')
            
            current_item_index += 1
        else:
            # Hide the item
            item['widgets']['button'].place_forget()
            canvas.itemconfig(item['widgets']['background'], state='hidden')
            canvas.itemconfig(item['widgets']['qty_text'], state='hidden')

# --- NEW: TAB BUTTONS ---
tab_button_y = 129
tab_button_all = Button(window, text="All", command=lambda: show_tab("All"), relief="flat", bg="#2E2E2E", fg="white", activebackground="#4f4f4f", activeforeground="white")
tab_button_all.place(x=49, y=tab_button_y, width=70, height=25)

tab_button_weapon = Button(window, text="Weapon", command=lambda: show_tab("Weapon"), relief="flat", bg="#2E2E2E", fg="white", activebackground="#4f4f4f", activeforeground="white")
tab_button_weapon.place(x=129, y=tab_button_y, width=70, height=25)

tab_button_accessory = Button(window, text="Accessory", command=lambda: show_tab("Accessory"), relief="flat", bg="#2E2E2E", fg="white", activebackground="#4f4f4f", activeforeground="white")
tab_button_accessory.place(x=209, y=tab_button_y, width=70, height=25)

tab_button_misc = Button(window, text="Misc", command=lambda: show_tab("Misc"), relief="flat", bg="#2E2E2E", fg="white", activebackground="#4f4f4f", activeforeground="white")
tab_button_misc.place(x=289, y=tab_button_y, width=70, height=25)

# --- MODIFIED: INVENTORY POPULATION ---
with open("Files/Player Data/Inventory.json", 'r') as fson:
    data=ujson.load(fson)
rol = list(data.keys())

# These lists still hold image references to prevent garbage collection
button_images_ref = []
item_images_ref = []

x_start, y_start = 49, 171
spacing_x, spacing_y = 100, 100
buttons_per_row = 8
image5_path = relative_to_assets("image_5.png")

for key in rol: # Loop through all items, not just the first 24
    item_data = {
        "name": key,
        "tr_n": thesystem.inventory.inventory_name_cut(key),
        "qty": data[key][0].get('qty', ''), "cat": data[key][0].get('cat', ''),
        "rank": data[key][0].get('rank', ''), "desc": data[key][0].get('desc', ''),
        "buff": data[key][0].get('buff', ''), "debuff": data[key][0].get('debuff', '')
    }
    
    # We call our new, improved function. Note the dummy x, y values (0,0)
    # as the show_tab function will handle the actual placement.
    item_bundle = thesystem.inventory.create_inventory_item(
        canvas, window, item_data, 0, 0, button_images_ref, item_images_ref, image5_path
    )
    inventory_items.append(item_bundle)

# --- Side Panels and Overlays ---
side = PhotoImage(file=relative_to_assets("blue.png") if job.upper() == "NONE" else relative_to_assets("purple.png"))
canvas.create_image(-10.0, 283.0, image=side)
canvas.create_image(851.0, 308.0, image=side)
canvas.create_rectangle(0.0, 0.0, 101.0, 21.0, fill=transp_clr, outline="")
canvas.create_rectangle(0.0, 520.0, 1000.0, 716.0, fill=transp_clr, outline="")
canvas.create_rectangle(0.0, 0.0, 1000.0, 34.0, fill=transp_clr, outline="")

image_40 = thesystem.system.side_bar("left_bar.png", (101, 520))
canvas.create_image(-13.0, 280.0, image=image_40)
image_50 = thesystem.system.side_bar("right_bar.png", (80, 500))
canvas.create_image(851.0, 280.0, image=image_50)

# --- Top and Bottom Bar Animation ---
image_index = 0
bot_image_index = 0
top_image = canvas.create_image(472.0, 20.0, image=top_preloaded_images[image_index])
canvas.tag_bind(top_image, "<ButtonPress-1>", start_move)
canvas.tag_bind(top_image, "<B1-Motion>", move_window)
bottom_image = canvas.create_image(427.0, 530.0, image=bottom_preloaded_images[bot_image_index])

def update_images():
    global image_index, bot_image_index
    image_index = (image_index + 1) % len(top_preloaded_images)
    top_img = top_preloaded_images[image_index]
    canvas.itemconfig(top_image, image=top_img)
    canvas.top_img = top_img
    bot_image_index = (bot_image_index + 1) % len(bottom_preloaded_images)
    bot_img = bottom_preloaded_images[bot_image_index]
    canvas.itemconfig(bottom_image, image=bot_img)
    canvas.bot_img = bot_img
    window.after(1000 // 24, update_images)

if setting_data["Settings"]["Performernce (ANIME):"] != "True":
    update_thread = threading.Thread(target=update_images)
    update_thread.daemon = True
    update_thread.start()

# --- Close Button ---
button_image_26 = PhotoImage(file=relative_to_assets("button_26.png"))
button_26 = Button(image=button_image_26, borderwidth=0, highlightthickness=0, command=lambda: ex_close(window), relief="flat")
button_26.place(x=806.0, y=64.0, width=20.0, height=20.0)

# --- FINAL SETUP ---
show_tab("All") # Show the "All" tab by default when the window opens
window.resizable(False, False)
window.mainloop()