# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJhadav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess
import csv
import ujson
import cv2
from PIL import Image, ImageTk
import threading
import sys
import os
import numpy as np
import random

current_dir = os.path.dirname(os.path.abspath(__file__))

project_root = os.path.abspath(os.path.join(current_dir, '../../'))

sys.path.insert(0, project_root)

import thesystem.equipmentbk
import thesystem.misc
import thesystem.system
import thesystem.equipmentbk as equipment
import thesystem.inventory
import thesystem.itemequip
from thesystem.misc import resource_path


window = Tk()

stop_event=threading.Event()

initial_height = 0
target_height = 555
window_width = 957

window.geometry(f"{window_width}x{initial_height}")
job=thesystem.misc.return_status()["status"][1]["job"]

top_val='dailyquest.py'
all_prev=''
video='Video'
transp_clr='#0C679B'

if job!='None':
    top_val=''
    all_prev='alt_'
    video='Alt Video'
    transp_clr='#652AA3'

thesystem.system.make_window_transparent(window,transp_clr)

with open("Files/Player Data/Settings.json", 'r') as settings_open:
    setting_data=ujson.load(settings_open)

thesystem.system.animate_window_open(window, target_height, window_width, step=30, delay=1)

window.configure(bg = "#FFFFFF")
set_data=thesystem.misc.return_settings()
transp_value=set_data["Settings"]["Transparency"]

window.attributes('-alpha',transp_value)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

# Preload top and bottom images
top_images = f"thesystem/{all_prev}top_bar"
bottom_images = f"thesystem/{all_prev}bottom_bar"

top_preloaded_images = thesystem.system.load_or_cache_images(top_images, (957, 43), job, type_="top")
bottom_preloaded_images = thesystem.system.load_or_cache_images(bottom_images, (1026, 47), job, type_="bottom")

subprocess.Popen([sys.executable, resource_path('Files/Mod/default/sfx.py')])

debuff_1_name=''
debuff_2_name=''
debuff_1='-'
debuff_2='-'

buff_1_name=''
buff_2_name=''
buff_1='-'
buff_2='-'

desc1=desc2=''
segments = []
segment_length = 77

def start_move(event):
    window.lastx, window.lasty = event.widget.winfo_pointerxy()

def move_window(event):
    x_root, y_root = event.widget.winfo_pointerxy()
    deltax, deltay = x_root - window.lastx, y_root - window.lasty

    if deltax != 0 or deltay != 0:  # Update only if there is actual movement
        window.geometry(f"+{window.winfo_x() + deltax}+{window.winfo_y() + deltay}")
        window.lastx, window.lasty = x_root, y_root


def ex_close(win):
    # This function now correctly closes the current window and re-opens the main inventory
    if setting_data["Settings"]["Performernce (ANIME):"] != "True":
        stop_event.set()
        if 'update_thread' in globals() and update_thread.is_alive():
            update_thread.join()
    threading.Thread(target=thesystem.system.fade_out, args=(window, 0.8)).start()
    subprocess.Popen([sys.executable, resource_path('Files/Mod/default/sfx_close.py')])
    subprocess.Popen([sys.executable, resource_path('Anime Version/Inventory/gui.py')])
    thesystem.system.animate_window_close(window, 0, window_width, step=20, delay=1)


typs='Item'

with open('Files/Temp Files/Inventory temp.csv', 'r') as fout:
    fr=csv.reader(fout)
    for k in fr:
        name=k[0]   
        try:
            qty=k[1]
            typs=k[2]
        except IndexError:
            typs='Item'
            qty=1 # Default quantity if not provided

with open('Files/Player Data/Equipment.json', 'r') as eq_fout:
    eq_data=ujson.load(eq_fout)

equiipment_check = equipment.find_item_slot(name, eq_data)
equiipment_check_bool=equiipment_check[1]


# --- FIX: ROBUST DATA LOADING ---
# This block now safely loads data and handles cases where an item might not be found.
item_data_source = None
try:
    if typs=='Item':
        with open("Files/Player Data/Inventory.json", 'r') as fson:
            data=ujson.load(fson)
    elif typs=='Preview':
        with open("Files/Data/Inventory_List.json", 'r') as fson:
            data=ujson.load(fson)

    item_data_source = data[name][0]

except (KeyError, FileNotFoundError):
    # If item not found or file is missing, we create default placeholder data
    item_data_source = {
        "rank": "N/A", "cat": "Unknown", "desc": "No data available for this item.",
        "Value": 0, "qty": qty, "buff": {}, "debuff": {}
    }

# Now, we unpack the data from the source (either the file or our default)
rank = item_data_source.get("rank", "N/A")
cat = item_data_source.get("cat", "Unknown")
n_cat = cat
if cat.upper() in ["FIRST GAUNTLET", "SECOND GAUNTLET"]:
    n_cat = "GAUNTLET"

if typs != 'Item':
    qty = item_data_source.get("qty", 1)

desc_full = item_data_source.get("desc", "")
for i in range(0, len(desc_full), segment_length):
    segments.append(desc_full[i:i+segment_length])

if len(segments) >= 1:
    desc1 = segments[0]
if len(segments) >= 2:
    desc2 = segments[1]

val = item_data_source.get('Value', 0)
item_full_data = {name: [item_data_source]}

buff = item_data_source.get("buff", {})
buff_1_name, buff_1, buff_2_name, buff_2 = thesystem.equipmentbk.process_attributes(buff, "buff")

debuff = item_data_source.get("debuff", {})
debuff_1_name, debuff_1, debuff_2_name, debuff_2 = thesystem.equipmentbk.process_attributes(debuff, "debuff")
# --- END FIX ---


with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    get_stuff_path_str=pres_file_data["Anime"]["Mid Size Screen"]

def get_stuff_path(key):
    full_path=get_stuff_path_str+'/'+key
    return full_path

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 555,
    width = 957,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=get_stuff_path("image_1.png"))
image_1 = canvas.create_image(
    478.0,
    277.0,
    image=image_image_1
)

with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    video_path=pres_file_data["Anime"][video]
    prealoaded_frames=np.load(video_path)
player = thesystem.system.FastVideoPlayer(canvas, prealoaded_frames, 478.0, 277.0, pause_duration=0.4)

image_image_2 = PhotoImage(
    file=get_stuff_path("frame.png"))
image_2 = canvas.create_image(
    482.976318359375,
    283.0,
    image=image_image_2
)

canvas.create_rectangle(
    346.0,
    111.0,
    758.0,
    147.0,
    fill="#303030",
    outline="")

canvas.create_text(
    347.0,
    112.0,
    anchor="nw",
    text="Item:",
    fill="#FFFFFF",
    font=("Montserrat Regular", 24 * -1)
)

canvas.create_text(
    407.0,
    112.0,
    anchor="nw",
    text=name,
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 24 * -1)
)

canvas.create_text(
    346.0,
    175.0,
    anchor="nw",
    text="Acquisition Difficulty:",
    fill="#FFFFFF",
    font=("Montserrat Light", 14 * -1)
)

canvas.create_text(
    204.0,
    411.0,
    anchor="nw",
    text=desc2,
    fill="#FFFFFF",
    font=("Montserrat Light", 14 * -1)
)

canvas.create_text(
    204.0,
    391.0,
    anchor="nw",
    text=desc1,
    fill="#FFFFFF",
    font=("Montserrat Light", 14 * -1)
)

canvas.create_text(
    346.0,
    196.0,
    anchor="nw",
    text=f"{rank}",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    355.0,
    196.0,
    anchor="nw",
    text="-rank",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    287.0,
    272.0,
    anchor="nw",
    text="-BUFF: ",
    fill="#4CFF73",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    347.0,
    272.0,
    anchor="nw",
    text=f"-{buff_1_name} {buff_1}",
    fill="#FFFFFF",
    font=("Montserrat Light", 15 * -1)
)

canvas.create_text(
    347.0,
    294.0,
    anchor="nw",
    text=f"-{buff_2_name} {buff_2}",
    fill="#FFFFFF",
    font=("Montserrat Light", 15 * -1)
)

canvas.create_text(
    287.0,
    333.0,
    anchor="nw",
    text="-DEBUFF: ",
    fill="#FF4C4C",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    367.0,
    333.0,
    anchor="nw",
    text=f"-{debuff_1_name} {debuff_1}",
    fill="#FFFFFF",
    font=("Montserrat Light", 15 * -1)
)

canvas.create_text(
    367.0,
    353.0,
    anchor="nw",
    text=f"-{debuff_2_name} {debuff_2}",
    fill="#FFFFFF",
    font=("Montserrat Light", 15 * -1)
)

canvas.create_text(
    528.0,
    196.0,
    anchor="nw",
    text=n_cat,
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    528.0,
    175.0,
    anchor="nw",
    text="Category:",
    fill="#FFFFFF",
    font=("Montserrat Light", 14 * -1)
)

canvas.create_text(
    637.0,
    198.0,
    anchor="nw",
    text=f"{val:,}",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    637.0,
    177.0,
    anchor="nw",
    text="Value:",
    fill="#FFFFFF",
    font=("Montserrat Light", 14 * -1)
)

canvas.create_text(
    740.0,
    198.0,
    anchor="nw",
    text=qty,
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    740.0,
    177.0,
    anchor="nw",
    text="Qty",
    fill="#FFFFFF",
    font=("Montserrat Light", 14 * -1)
)

canvas.create_rectangle(
    149.0,
    99.0,
    279.0,
    229.0,
    fill="#2E2E2E",
    outline="")

# Define the target size for the item icon box
desired_size = (125, 125)

# IMPORTANT: You may need to adjust this path to where your item images are stored.
# This is a common path structure, but yours might be different.

# Create a filename-safe version of the name by removing the apostrophe
image_name = name.replace("'", "") # <-- ADD THIS LINE

image_path = f"Files\Mod\default\icons\{image_name}.png" 

try:
    # Open the original image file
    original_image = Image.open(resource_path(image_path))

    # Resize it to the desired size using a high-quality filter
    resized_image = original_image.resize(desired_size, Image.Resampling.LANCZOS)

    # Convert the resized image for use in Tkinter
    image_image_3 = ImageTk.PhotoImage(resized_image)

except FileNotFoundError:
    # If the image file doesn't exist, create a blank placeholder
    placeholder = Image.new('RGBA', desired_size, (50, 50, 50, 255))
    image_image_3 = ImageTk.PhotoImage(placeholder)

image_3 = canvas.create_image(
    214.0,
    164.0,
    image=image_image_3
)

if typs=='Item':

    button_image_1 = PhotoImage(
        file=get_stuff_path("sell.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (equipment.finish(qty=qty, equipment_check=equiipment_check),thesystem.inventory.selling_item(name,window,val)),
        relief="flat"
    )
    button_1.place(
        x=622.0,
        y=445.0,
        width=135.0,
        height=25.0
    )

    if equiipment_check_bool:
        canvas.create_text(
            500.0,
            480.0,
            anchor="nw",
            text="Already Equipped!",
            fill="#FFD337",
            font=("Exo Bold", 13 * -1)
        )

    button_image_2 = PhotoImage(
        file=get_stuff_path("equip.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: equip_with_srank_levelup(),
        relief="flat"
    )
    button_2.place(
        x=774.0,
        y=445.0,
        width=76.0,
        height=25.0
    )

    def equip_with_srank_levelup():
        if rank == 'S' and random.random() < 0.10: # 10% chance
            with open("Files/Player Data/Status.json", 'r') as status_file:
                status_data = ujson.load(status_file)
            status_data["status"][0]["level"] += 1
            with open("Files/Player Data/Status.json", 'w') as status_file:
                ujson.dump(status_data, status_file, indent=4)
            
            # Show a message that stays for a moment before equipping
            level_up_text = canvas.create_text(
                480.0, 415.0,
                anchor="center",
                text="S-RANK BONUS! LEVEL UP!",
                fill="#FFD700",
                font=("Montserrat Bold", 18 * -1)
            )
            # Wait 1.5 seconds before equipping, then remove the text
            window.after(1500, lambda: (
                thesystem.itemequip.equip_item(cat, item_full_data, window),
                canvas.delete(level_up_text)
            ))
        else:
            thesystem.itemequip.equip_item(cat, item_full_data, window)

    button_image_3 = PhotoImage(
        file=get_stuff_path("return.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: ex_close(window),
        relief="flat"
    )
    button_3.place(
        x=819.0,
        y=64.0,
        width=40.0,
        height=40.0
    )

else:
    button_image_3 = PhotoImage(
        file=get_stuff_path("return.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: ex_close(window),
        relief="flat"
    )
    button_3.place(
        x=819.0,
        y=64.0,
        width=40.0,
        height=40.0
    )


side = PhotoImage(file=get_stuff_path("blue.png"))
if job.upper()!="NONE":
    side = PhotoImage(file=get_stuff_path("purple.png"))

canvas.create_image(35.0, 270.0, image=side)
canvas.create_image(925.0, 294.0, image=side)

canvas.create_rectangle(
    0.0,
    0.0,
    240.0,
    24.0,
    fill=transp_clr,
    outline="")

canvas.create_rectangle(
    0.0,
    513.0,
    925.0,
    555.0,
    fill=transp_clr,
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    957.0,
    36.0,
    fill=transp_clr,
    outline="")

image_40 = thesystem.system.side_bar("left_bar.png", (60, 490))
canvas.create_image(50.0, 270.0, image=image_40)

image_50 = thesystem.system.side_bar("right_bar.png", (60, 490))
canvas.create_image(900.0, 275.0, image=image_50)

image_index = 0
bot_image_index = 0

top_image = canvas.create_image(
    478.0,
    21.0,
    image=top_preloaded_images[image_index]
)

canvas.tag_bind(top_image, "<ButtonPress-1>", start_move)
canvas.tag_bind(top_image, "<B1-Motion>", move_window)

bottom_image = canvas.create_image(
    480.0,
    530.0,
    image=bottom_preloaded_images[bot_image_index]
)

step,delay=1,1

def update_images():
    global image_index, bot_image_index

    image_index = (image_index + 1) % len(top_preloaded_images)
    top_img = top_preloaded_images[image_index]
    canvas.itemconfig(top_image, image=top_img)
    canvas.top_img = top_img

    bot_image_index = (bot_image_index + 1) % len(bottom_preloaded_images)
    bot_img = bottom_preloaded_images[bot_image_index]
    canvas.itemconfig(bottom_image, image=bot_img)
    canvas.bot_img = bot_img

    if not stop_event.is_set():
        window.after(1000 // 24, update_images)

# Start the animation
if setting_data["Settings"]["Performernce (ANIME):"] != "True":
    update_thread = threading.Thread(target=update_images)
    update_thread.daemon = True
    update_thread.start()

window.resizable(False, False)
window.mainloop()