# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import csv
import ujson
import subprocess
import threading
import cv2
from PIL import Image, ImageTk, ImageDraw
import sys
import os
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))

project_root = os.path.abspath(os.path.join(current_dir, '../../'))

sys.path.insert(0, project_root)

import thesystem.equipmentbk
import thesystem.system
import thesystem.inventory
import thesystem.equipmentbk as equipment
from thesystem.misc import resource_path

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")

with open("Files/Player Data/Tabs.json",'r') as tab_son:
    tab_son_data=ujson.load(tab_son)

with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
    tab_son_data["Equipment"]='Open'
    ujson.dump(tab_son_data,fin_tab_son,indent=4)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
stop_event=threading.Event()

initial_height = 0
target_height = 555
window_width = 957

window.geometry(f"{window_width}x{initial_height}")

job=thesystem.misc.return_status()["status"][1]["job"]

top_val='dailyquest.py'
all_prev=''
video='Video'
transp_clr='#0C679B'

if job!='None':
    top_val=''
    all_prev='alt_'
    video='Alt Video'
    transp_clr='#652AA3'

thesystem.system.make_window_transparent(window,transp_clr)

with open("Files/Player Data/Settings.json", 'r') as settings_open:
    setting_data=ujson.load(settings_open)


thesystem.system.animate_window_open(window, target_height, window_width, step=50, delay=1)
window.configure(bg = "#FFFFFF")
set_data=thesystem.misc.return_settings()
transp_value=set_data["Settings"]["Transparency"]

window.attributes('-alpha',transp_value)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

top_images = f"thesystem/{all_prev}top_bar"
bottom_images = f"thesystem/{all_prev}bottom_bar"

top_preloaded_images = thesystem.system.load_or_cache_images(top_images, (970, 40), job, type_="top")
bottom_preloaded_images = thesystem.system.load_or_cache_images(bottom_images, (970, 40), job, type_="bottom")

subprocess.Popen([sys.executable, resource_path('Files/Mod/default/sfx.py')])

def start_move(event):
    window.lastx, window.lasty = event.widget.winfo_pointerxy()

def move_window(event):
    x_root, y_root = event.widget.winfo_pointerxy()
    deltax, deltay = x_root - window.lastx, y_root - window.lasty

    if deltax != 0 or deltay != 0:  # Update only if there is actual movement
        window.geometry(f"+{window.winfo_x() + deltax}+{window.winfo_y() + deltay}")
        window.lastx, window.lasty = x_root, y_root

def ex_close():
    if setting_data["Settings"]["Performernce (ANIME):"] != "True":
        stop_event.set()
        if 'update_thread' in globals() and update_thread.is_alive():
            update_thread.join()
    with open("Files/Player Data/Tabs.json",'r') as tab_son:
        tab_son_data=ujson.load(tab_son)

    if tab_son_data["Equipment"]=='Open':

        with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
            tab_son_data["Equipment"]='Close'
            ujson.dump(tab_son_data,fin_tab_son,indent=4)

    threading.Thread(target=thesystem.system.fade_out, args=(window, 0.8)).start()
    subprocess.Popen([sys.executable, resource_path('Files/Mod/default/sfx_close.py')])
    thesystem.system.animate_window_close(window, 0, window_width, step=20, delay=1)

def split_text(text, segment_length):
    # Check if the text length exceeds the segment length
    if len(text) > segment_length:
        # Find the last space within the segment length to avoid splitting a word
        split_point = text.rfind(" ", 0, segment_length)
        
        # If there's no space, we have to split at the exact segment length
        if split_point == -1:
            split_point = segment_length
        
        # Split text at the identified point
        part1 = text[:split_point]
        part2 = text[split_point:].lstrip()  # Remove leading spaces in part2
    else:
        # If text is within the segment length, assign it all to part1 and leave part2 empty
        part1 = text
        part2 = ""
    
    return part1, part2

def open_select(cat):
    fout=open('Files/Temp Files/Equipment Temp.csv', 'w', newline='')
    fw=csv.writer(fout)
    rec=[cat]
    fw.writerow(rec)
    fout.close()

    subprocess.Popen([sys.executable, resource_path('Anime Version/Equip Item/gui.py')])

    ex_close()

def set_effect_open():
    subprocess.Popen([sys.executable, resource_path('Anime Version/Set Effects/gui.py')])

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 555,
    width = 957,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    478.0,
    277.0,
    image=image_image_1
)

with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    video_path=pres_file_data["Anime"][video]
    preloaded_frames=np.load(video_path)
player = thesystem.system.FastVideoPlayer(canvas, preloaded_frames, 478.0, 277.0, pause_duration=0.3)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    469.9760437011719,
    276.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    477.0,
    287.9999999999999,
    image=image_image_3
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    212.0,
    115.0,
    image=image_image_5
)

# ! ============================================================================
# ! Title
# ! ============================================================================

canvas.create_text(
    136.0,
    97.0,
    anchor="nw",
    text="EQUIPMENT",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 24 * -1)
)

# ! ============================================================================
# ! INFO JSON RETRIEVAL (MODIFIED FOR WEAPONS)
# ! ============================================================================

helm = chest = weapon1 = weapon2 = boot = ring = collar = '-'
helmboost_1 = helmboost_2 = ''
chestboost_1 = chestboost_2 = ''
weapon1_boost_1 = weapon1_boost_2 = ''
weapon2_boost_1 = weapon2_boost_2 = ''
bootboost_1 = bootboost_2 = ''
ringboost_1 = ringboost_2 = ''
collarboost_1 = collarboost_2 = ''

max_width, max_height = 164/1.5, 126/1.5

def assign_equipment(equipment_list):
    global helm, chest, weapon1, weapon2, boot, ring, collar
    global helmboost_1, helmboost_2, chestboost_1, chestboost_2
    global weapon1_boost_1, weapon1_boost_2, weapon2_boost_1, weapon2_boost_2
    global bootboost_1, bootboost_2, ringboost_1, ringboost_2
    global collarboost_1, collarboost_2

    # Unpack equipment items and boosts from the list
    equipment_items, equipment_boosts = equipment_list

    # Assign values to the equipment variables
    helm, chest, weapon1, weapon2, boot, ring, collar = equipment_items
    (helmboost_1, helmboost_2, chestboost_1, chestboost_2, 
     weapon1_boost_1, weapon1_boost_2, weapon2_boost_1, weapon2_boost_2, 
     bootboost_1, bootboost_2, ringboost_1, ringboost_2, 
     collarboost_1, collarboost_2) = equipment_boosts

equipment_list=equipment.get_equipment()
assign_equipment(equipment_list)

# ! ============================================================================
# ! ROTATING 3D PLAYER MODEL (NEW)
# ! ============================================================================

def generate_rotating_humanoid_frames(size, num_frames=72):
    """
    Generates frames for a rotating 3D wireframe humanoid model.
    """
    frames = []
    
    # Define the joints of a simple humanoid stick figure. Y is the vertical axis.
    # Y-coordinates are inverted to make the model right-side up on the canvas.
    points = np.array([
        [0, -2.5, 0],   # 0: Head top
        [0, -1.8, 0],   # 1: Neck
        [-1.2, -1.5, 0],# 2: Left Shoulder
        [1.2, -1.5, 0], # 3: Right Shoulder
        [-1.2, 0, 0],   # 4: Left Hand
        [1.2, 0, 0],    # 5: Right Hand
        [0, 1, 0],      # 6: Hip center
        [-0.8, 1.2, 0], # 7: Left Hip
        [0.8, 1.2, 0],  # 8: Right Hip
        [-0.8, 3, 0],   # 9: Left Foot
        [0.8, 3, 0]     # 10: Right Foot
    ])

    # Define the bones (edges) connecting the joints
    edges = [
        (1, 2), (1, 3), (2, 4), (3, 5), # Arms
        (1, 6), # Torso
        (6, 7), (6, 8), # Hips
        (7, 9), (8, 10) # Legs
    ]
    
    head_center_index = 0
    head_radius = 0.7 # in 3D space units

    canvas_size = int(size * 8) # Make canvas large enough for the model
    center_offset = canvas_size / 2

    for i in range(num_frames):
        angle_y = (i * 2 * np.pi / num_frames)
        
        # Define rotation matrix for a simple turntable rotation around the Y-axis
        rot_y = np.array([[np.cos(angle_y), 0, np.sin(angle_y)],
                          [0, 1, 0],
                          [-np.sin(angle_y), 0, np.cos(angle_y)]])
        
        # Rotate points
        rotated_points = np.dot(points, rot_y)
        
        # Project 3D points to 2D for rendering
        projected_points = (rotated_points[:, :2] * size) + center_offset
        
        # Create a blank image with a transparent background
        image = Image.new("RGBA", (canvas_size, canvas_size), (0, 0, 0, 0))
        draw = ImageDraw.Draw(image)
        
        # Draw the bones
        line_color = "#AFEEEE" # Pale Turquoise, good for a hologram effect
        for edge in edges:
            p1 = projected_points[edge[0]]
            p2 = projected_points[edge[1]]
            draw.line((p1[0], p1[1], p2[0], p2[1]), fill=line_color, width=3)
            
        # Draw the head as a circle
        head_pos_2d = projected_points[head_center_index]
        r = head_radius * size 
        draw.ellipse((head_pos_2d[0]-r, head_pos_2d[1]-r, head_pos_2d[0]+r, head_pos_2d[1]+r), outline=line_color, width=3)
            
        frames.append(ImageTk.PhotoImage(image))
        
    return frames

# Load all the frames for the rotating model animation
model_frames = generate_rotating_humanoid_frames(25) # Size 25
model_frame_index = 0

# Create the image object on the canvas that will be animated
model_image_obj = canvas.create_image(
    479.0,
    278.0,
    image=model_frames[model_frame_index]
)

def update_model_animation():
    """
    Cycles through the pre-loaded frames to animate the player model.
    """
    global model_frame_index
    # Move to the next frame, looping back to the start
    model_frame_index = (model_frame_index + 1) % len(model_frames)
    # Update the canvas item with the new frame
    canvas.itemconfig(model_image_obj, image=model_frames[model_frame_index])
    # Schedule the next frame update (50ms delay for ~20 FPS)
    window.after(50, update_model_animation)

# Start the animation loop
update_model_animation()


# ! ============================================================================
# ! Armor/Weapon Display (MODIFIED FOR WEAPONS)
# ! ============================================================================

# Replaced gauntlets with weapons
weapon2_image = (thesystem.equipmentbk.get_armor_image(weapon2))
weapon2_im = canvas.create_image(
    479.0,
    278.0,
    image=weapon2_image
)

weapon1_image = (thesystem.equipmentbk.get_armor_image(weapon1))
weapon1_im = canvas.create_image(
    479.0,
    278.0,
    image=weapon1_image
)


# ? ====================================================================
# ? Weapon 1 Part (Formerly First Gauntlet)
# ? ====================================================================

image_image_8 = thesystem.inventory.get_item_button_image(weapon1, max_width, max_height)
image_8 = canvas.create_image(
    164.0,
    381.0,
    image=image_image_8
)

canvas.create_text(
    208.0,
    363.0,
    anchor="nw",
    text=weapon1,
    fill="#FFFFFF",
    font=("Montserrat Regular", 11 * -1)
)

canvas.create_text(
    208.0,
    380.0,
    anchor="nw",
    text='-'+weapon1_boost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    208.0,
    395.0,
    anchor="nw",
    text='-'+weapon1_boost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("WEAPON 1"),
    relief="flat"
)
button_3.place(
    x=207.0,
    y=346.0,
    width=12.0,
    height=12.0
)
# ? ====================================================================
# ? Weapon 2 Part (Formerly Second Gauntlet)
# ? ====================================================================

image_image_12 = thesystem.inventory.get_item_button_image(weapon2, max_width, max_height)
image_12 = canvas.create_image(
    684.0,
    226.0,
    image=image_image_12
)

segment_length = 30
w2_part1, w2_part2 = split_text(weapon2, segment_length)

if len(weapon2)<31:
    canvas.create_text(
        730.0,
        202.0,
        anchor="nw",
        text=weapon2,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

else:
    canvas.create_text(
        730.0,
        202.0,
        anchor="nw",
        text=w2_part1,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

    canvas.create_text(
        730.0,
        214.0,
        anchor="nw",
        text=w2_part2,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

canvas.create_text(
    730.0,
    215.0+12,
    anchor="nw",
    text='-'+weapon2_boost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    730.0,
    230.0+12,
    anchor="nw",
    text='-'+weapon2_boost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("WEAPON 2"),
    relief="flat"
)
button_7.place(
    x=628.0,
    y=190.0,
    width=12.0,
    height=12.0
)

side = PhotoImage(file=relative_to_assets("blue.png"))
if job.upper()!="NONE":
    side = PhotoImage(file=relative_to_assets("purple.png"))
canvas.create_image(36.0, 275.0, image=side)
canvas.create_image(926.0, 290.0, image=side)

canvas.create_rectangle(
    0.0,
    0.0,
    101.0,
    21.0,
    fill=transp_clr,
    outline="")

canvas.create_rectangle(
    0.0,
    520.0,
    1000.0,
    716.0,
    fill=transp_clr,
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1000.0,
    34.0,
    fill=transp_clr,
    outline="")

image_40 = thesystem.system.side_bar("left_bar.png", (101, 500))
canvas.create_image(36.0, 275.0, image=image_40)

image_50 = thesystem.system.side_bar("right_bar.png", (80, 505))
canvas.create_image(910.0, 278.0, image=image_50)

image_index = 0
bot_image_index = 0

top_image = canvas.create_image(
    472.0,
    20.0,
    image=top_preloaded_images[image_index]
)

canvas.tag_bind(top_image, "<ButtonPress-1>", start_move)
canvas.tag_bind(top_image, "<B1-Motion>", move_window)

bottom_image = canvas.create_image(
    470.0,
    530.0,
    image=bottom_preloaded_images[bot_image_index]
)

step,delay=1,1

def update_images():
    global image_index, bot_image_index

    if not stop_event.is_set():
        image_index = (image_index + 1) % len(top_preloaded_images)
        top_img = top_preloaded_images[image_index]
        canvas.itemconfig(top_image, image=top_img)
        canvas.top_img = top_img

        bot_image_index = (bot_image_index + 1) % len(bottom_preloaded_images)
        bot_img = bottom_preloaded_images[bot_image_index]
        canvas.itemconfig(bottom_image, image=bot_img)
        canvas.bot_img = bot_img

        window.after(1000 // 24, update_images)

# Start the animation
if setting_data["Settings"]["Performernce (ANIME):"] != "True":
    update_thread = threading.Thread(target=update_images)
    update_thread.daemon = True
    update_thread.start()

# ===========================================================

image_image_25 = PhotoImage(
    file=relative_to_assets("image_25.png"))
image_25 = canvas.create_image(
    318.0,
    108.0,
    image=image_image_25
)

canvas.tag_bind(image_25, "<ButtonPress-1>", lambda event: thesystem.system.info_open("Equipment"))

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ex_close(),
    relief="flat"
)
button_9.place(
    x=838.0,
    y=57.0,
    width=26.0,
    height=26.0
)

window.resizable(False, False)
window.mainloop()
